-- AlterTable
ALTER TABLE "activities" ADD COLUMN IF NOT EXISTS "loop_polygon_geojson" JSONB,
ADD COLUMN IF NOT EXISTS "loop_min_lng" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "loop_min_lat" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "loop_max_lng" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "loop_max_lat" DOUBLE PRECISION;
