/**
 * Badge definitions: key, tiered, tiers, name, description, icon, category, isSecret, condition(stats) => tier (1..n) or 0.
 * Non-tiered badges use tier 1 when unlocked. Tiered badges use tiers[0..n] thresholds; condition returns highest tier reached.
 */

const METERS_PER_MILE = 1609.344;

export const BADGE_CATEGORIES = ['activity', 'territory', 'social', 'secret'];

/** @param {Record<string, number>} stats */
function tierReached(thresholds, value) {
  let t = 0;
  for (let i = 0; i < thresholds.length; i++) {
    if (value >= thresholds[i]) t = i + 1;
  }
  return t;
}

export const BADGE_DEFINITIONS = [
  // —— Activity ——
  {
    key: 'first_run',
    tiered: false,
    name: 'First Steps',
    description: 'Complete your first synced run',
    icon: '👟',
    category: 'activity',
    isSecret: false,
    condition: (stats) => (stats.totalActivities >= 1 ? 1 : 0),
  },
  {
    key: 'total_miles',
    tiered: true,
    tiers: [10, 50, 100, 500],
    name: 'Distance Explorer',
    description: 'Total miles run',
    icon: '📏',
    category: 'activity',
    isSecret: false,
    condition: (stats) => tierReached([10, 50, 100, 500], stats.totalMiles ?? 0),
  },
  {
    key: 'longest_run',
    tiered: true,
    tiers: [5, 10, 26.2, 50],
    name: 'Long Run',
    description: 'Longest single activity (miles)',
    icon: '🏃',
    category: 'activity',
    isSecret: false,
    condition: (stats) => tierReached([5, 10, 26.2, 50], stats.longestSingleActivityMiles ?? 0),
  },
  {
    key: 'streak',
    tiered: true,
    tiers: [3, 7, 30],
    name: 'Streak',
    description: 'Consecutive days with at least one activity',
    icon: '🔥',
    category: 'activity',
    isSecret: false,
    condition: (stats) => tierReached([3, 7, 30], stats.activeDayStreak ?? 0),
  },
  {
    key: 'loop_count',
    tiered: true,
    tiers: [1, 5, 10, 25],
    name: 'Loop Master',
    description: 'Activities that formed closed loops',
    icon: '🔄',
    category: 'activity',
    isSecret: false,
    condition: (stats) => tierReached([1, 5, 10, 25], stats.loopCount ?? 0),
  },
  // —— Territory ——
  {
    key: 'first_capture',
    tiered: false,
    name: 'First Capture',
    description: 'Claim your first territory loop',
    icon: '🏴',
    category: 'territory',
    isSecret: false,
    condition: (stats) => ((stats.totalOwnedAreaMi2 ?? 0) > 0 ? 1 : 0),
  },
  {
    key: 'area_sq_miles',
    tiered: true,
    tiers: [0.1, 1, 10, 50],
    name: 'Land Baron',
    description: 'Total territory area (mi²)',
    icon: '🗺️',
    category: 'territory',
    isSecret: false,
    condition: (stats) => tierReached([0.1, 1, 10, 50], stats.totalOwnedAreaMi2 ?? 0),
  },
  {
    key: 'cells_stolen',
    tiered: true,
    tiers: [1, 10, 50, 100],
    name: 'Conqueror',
    description: 'Cells captured from others',
    icon: '⚔️',
    category: 'territory',
    isSecret: false,
    condition: (stats) => tierReached([1, 10, 50, 100], stats.cellsStolen ?? 0),
  },
  {
    key: 'defended',
    tiered: true,
    tiers: [1, 5, 20, 50],
    name: 'Defender',
    description: 'Cells defended (re-ran your loop)',
    icon: '🛡️',
    category: 'territory',
    isSecret: false,
    condition: (stats) => tierReached([1, 5, 20, 50], stats.defendedCount ?? 0),
  },
  // —— Social ——
  {
    key: 'first_friend',
    tiered: false,
    name: 'First Friend',
    description: 'Add your first friend',
    icon: '🤝',
    category: 'social',
    isSecret: false,
    condition: (stats) => (stats.friendsCount >= 1 ? 1 : 0),
  },
  {
    key: 'friends_count',
    tiered: true,
    tiers: [3, 5, 10, 25],
    name: 'Squad',
    description: 'Number of friends',
    icon: '👥',
    category: 'social',
    isSecret: false,
    condition: (stats) => tierReached([3, 5, 10, 25], stats.friendsCount ?? 0),
  },
  // —— Secret ——
  {
    key: 'early_bird',
    tiered: false,
    name: 'Early Bird',
    description: 'Complete a run before 6:00 AM (local)',
    icon: '🌅',
    category: 'secret',
    isSecret: true,
    condition: (stats) => (stats.hasEarlyMorningActivity ? 1 : 0),
  },
  {
    key: 'night_owl',
    tiered: false,
    name: 'Night Owl',
    description: 'Complete a run after 10:00 PM (local)',
    icon: '🌙',
    category: 'secret',
    isSecret: true,
    condition: (stats) => (stats.hasLateNightActivity ? 1 : 0),
  },
  {
    key: 'marathoner',
    tiered: false,
    name: 'Marathoner',
    description: 'Run 26.2+ miles in a single activity',
    icon: '🏁',
    category: 'secret',
    isSecret: true,
    condition: (stats) => ((stats.longestSingleActivityMiles ?? 0) >= 26.2 ? 1 : 0),
  },
  {
    key: 'hundred_miles_week',
    tiered: false,
    name: 'Century Week',
    description: 'Run 100+ miles in a 7-day period',
    icon: '💯',
    category: 'secret',
    isSecret: true,
    condition: (stats) => (stats.maxMilesIn7Days >= 100 ? 1 : 0),
  },
  {
    key: 'lone_wolf',
    tiered: false,
    name: 'Lone Wolf',
    description: 'Claim 10+ loops with zero friends',
    icon: '🐺',
    category: 'secret',
    isSecret: true,
    condition: (stats) => (stats.friendsCount === 0 && (stats.loopCount ?? 0) >= 10 ? 1 : 0),
  },
  {
    key: 'first_sync',
    tiered: false,
    name: 'Connected',
    description: 'Sync Strava for the first time',
    icon: '🔗',
    category: 'secret',
    isSecret: true,
    condition: (stats) => (stats.totalActivities >= 1 && stats.hasEverSynced ? 1 : 0),
  },
  {
    key: 'five_loops_one_day',
    tiered: false,
    name: 'Loop Day',
    description: 'Capture 5+ loops in a single day',
    icon: '📅',
    category: 'secret',
    isSecret: true,
    condition: (stats) => (stats.maxLoopsInOneDay >= 5 ? 1 : 0),
  },
  {
    key: 'steal_spree',
    tiered: false,
    name: 'Steal Spree',
    description: 'Steal 5+ cells in a single activity',
    icon: '💨',
    category: 'secret',
    isSecret: true,
    condition: (stats) => (stats.maxCellsStolenInOneActivity >= 5 ? 1 : 0),
  },
  {
    key: 'weekend_warrior',
    tiered: false,
    name: 'Weekend Warrior',
    description: 'Run only on Saturday and Sunday for 4+ weeks',
    icon: '📆',
    category: 'secret',
    isSecret: true,
    condition: (stats) => (stats.weekendOnlyStreakWeeks >= 4 ? 1 : 0),
  },
  {
    key: 'ten_k',
    tiered: false,
    name: '10K',
    description: 'Complete a 10K run (6.2+ miles)',
    icon: '🎯',
    category: 'activity',
    isSecret: false,
    condition: (stats) => ((stats.longestSingleActivityMiles ?? 0) >= 6.2 ? 1 : 0),
  },
  {
    key: 'half_marathon',
    tiered: false,
    name: 'Half Marathon',
    description: 'Complete a half marathon (13.1+ miles)',
    icon: '🏅',
    category: 'activity',
    isSecret: false,
    condition: (stats) => ((stats.longestSingleActivityMiles ?? 0) >= 13.1 ? 1 : 0),
  },
  {
    key: 'hundred_miles',
    tiered: false,
    name: '100 Miles',
    description: 'Reach 100 total miles',
    icon: '💪',
    category: 'activity',
    isSecret: false,
    condition: (stats) => ((stats.totalMiles ?? 0) >= 100 ? 1 : 0),
  },
  {
    key: 'territory_initiate',
    tiered: false,
    name: 'Territory Initiate',
    description: 'Own at least 1 mi² of territory',
    icon: '📍',
    category: 'territory',
    isSecret: false,
    condition: (stats) => ((stats.totalOwnedAreaMi2 ?? 0) >= 1 ? 1 : 0),
  },
  {
    key: 'raider',
    tiered: false,
    name: 'Raider',
    description: 'Steal your first cell from another runner',
    icon: '⚡',
    category: 'territory',
    isSecret: false,
    condition: (stats) => ((stats.cellsStolen ?? 0) >= 1 ? 1 : 0),
  },
  {
    key: 'social_butterfly',
    tiered: false,
    name: 'Social Butterfly',
    description: 'Add 5 friends',
    icon: '🦋',
    category: 'social',
    isSecret: false,
    condition: (stats) => ((stats.friendsCount ?? 0) >= 5 ? 1 : 0),
  },
  {
    key: 'week_streak',
    tiered: false,
    name: 'Weekly Habit',
    description: '7-day activity streak',
    icon: '📈',
    category: 'activity',
    isSecret: false,
    condition: (stats) => ((stats.activeDayStreak ?? 0) >= 7 ? 1 : 0),
  },
  {
    key: 'month_streak',
    tiered: false,
    name: 'Monthly Grind',
    description: '30-day activity streak',
    icon: '🗓️',
    category: 'activity',
    isSecret: false,
    condition: (stats) => ((stats.activeDayStreak ?? 0) >= 30 ? 1 : 0),
  },
];

/** Get definition by key */
export function getBadgeDefinition(key) {
  return BADGE_DEFINITIONS.find((b) => b.key === key);
}

/** Tier label for display (I, II, III, IV) */
export const TIER_ROMAN = ['', 'I', 'II', 'III', 'IV', 'V'];
